# full supervision, segthor heart
data:
  dataset: BGDataset
  dataname: Prostate
  anisotropy: True   # True if (max_spacing/min_spacing>3)
  data_dir: '/group/lishl/weak_datasets/Promise12/1011_train_weak_percent_0.5_random/expand_mat/'
  use_weak: True

model:
  network: 'Generic_UNet'
  use_author_block: False   # default nnUNet params
  pre_model: ''
  pool_op_kernel_sizes: '[(1, 2, 2), (1, 2, 2), (2, 2, 2), (2, 2, 2), (2, 2, 2)]'   # (8, 32, 32)
  conv_kernel_sizes: '[(1, 3, 3), (1, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3)]'


train:
  n_epochs: 200 #100
  n_batches: 250  #250
  train_batch: 2 #4
  valid_batch: 1 #4

  loss_name: 'MultipleOutputLoss2' #'CEDiceLoss'  #
  with_dice_loss: 0
  fg_weight: 1  #16
  auto_weight_fg_bg: True
  draw_fgbg: False

  optimizer: SGD    # Adam
  momentum: 0.99
  lr: 1.0e-2
  lr_decay: 'poly'  #'plateau'
  min_lr: 1.0e-3