# full supervision, segthor heart
data:
  dataset: BGDataset
  dataname: Prostate
  anisotropy: True   # True if (max_spacing/min_spacing>3)
  data_dir: '/group/lishl/weak_datasets/Promise12/processed_train/normalize_mat/'
  use_weak: False

model:
  network: 'Generic_UNet'
  use_author_block: False   # default nnUNet params
  pre_model: ''
  pool_op_kernel_sizes: '[(1, 2, 2), (1, 2, 2), (2, 2, 2), (2, 2, 2), (2, 2, 2)]'   # calculated from final spacing and shape
  conv_kernel_sizes: '[(1, 3, 3), (1, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3)]'


train:
  n_epochs: 200
  n_batches: 250  #250
  train_batch: 2 #4
  valid_batch: 1 #4

  loss_name: 'MultipleOutputLoss2' #'CEDiceLoss'  #
  fg_weight: 1  #16

  optimizer: SGD    # Adam
  momentum: 0.99
  lr: 1.0e-2
  lr_decay: 'poly'  #'plateau'